export interface Pedido {
    id: number
    nome: string
    cpf: string
    telefone: string
    celular: string
    email: string
    cep: string
    logradouro: string
    numero: string
    complemento: string
    bairro: string
    cidade: string
    estado: string
    fantasia: string
    razaoSocial: string
    cnpj: string
    tipoPgto: string
    cepEntrega: string
    logradouroEntrega: string
    numeroEntrega: string
    complementoEntrega: string
    bairroEntrega: string
    cidadeEntrega: string
    estadoEntrega: string
    sfobras: string
    cno: string
    mangueira: string
    ie: string
    volume: string
    preco1: string
    preco2: string
    preco3: string
    preco4: string
    preco5: string
    preco6: string
    ajudanteHora: string
    observacao: string
    idPedido: string
    modelo: string
  }